export type Difficulty = 'easy' | 'medium' | 'hard' | 'warrior';

export const QUOTES_BY_DIFFICULTY: Record<Difficulty, string[]> = {
  easy: [
    "Stay hungry, stay foolish.",
    "Just keep swimming.",
    "May the Force be with you.",
    "Winter is coming.",
    "To infinity and beyond!",
    "Why so serious?",
    "I am inevitable.",
    "Hakuna Matata.",
    "I'll be back.",
    "You got this.",
    "Just do it.",
    "Keep moving forward.",
    "Believe you can.",
    "You are enough.",
    "Never give up.",
    "Think different.",
    "Stronger together.",
    "Dream big.",
    "Seize the day.",
    "Make it happen.",
  ],
  medium: [
    "The quick brown fox jumps over the lazy dog",
    "Simplicity is the soul of efficiency.",
    "First, solve the problem. Then, write the code.",
    "Talk is cheap. Show me the code.",
    "Quality is not an act, it is a habit.",
    "Action is the foundational key to all success.",
    "The secret of getting ahead is getting started.",
    "Success is the sum of small efforts repeated day in and day out.",
    "What we know is a drop, what we don't know is an ocean.",
    "Learning never exhausts the mind.",
    "Do or do not. There is no try.",
    "Not all those who wander are lost.",
    "With great power comes great responsibility.",
    "I find your lack of faith disturbing.",
    "Elementary, my dear Watson.",
    "Fortune favors the bold.",
    "Adventure is out there.",
    "Imagination is more important than knowledge.",
    "Life is what happens when you're busy making other plans.",
    "The only limit is your mind.",
  ],
  hard: [
    "Programs must be written for people to read, and only incidentally for machines to execute.",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.",
    "Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away.",
    "A good programmer is someone who looks both ways before crossing a one-way street.",
    "Before software can be reusable it first has to be usable.",
    "Premature optimization is the root of all evil.",
    "The function of good software is to make the complex appear simple.",
    "Experience is the name everyone gives to their mistakes.",
    "The best code is no code at all.",
    "Simplicity is prerequisite for reliability.",
    "Controlling complexity is the essence of computer programming.",
    "Testing leads to failure, and failure leads to understanding.",
    "The most effective debugging tool is still careful thought.",
    "Optimize for readability; machines will cope.",
    "If it hurts, do it more often.",
    "In theory, theory and practice are the same; in practice, they are not.",
    "There are only two hard things in Computer Science: cache invalidation and naming things.",
    "The purpose of abstraction is to create a new semantic level.",
    "Weeks of coding can save you hours of planning.",
    "Make it work, then make it right, then make it fast.",
  ],
  warrior: [
    "Supercalifragilisticexpialidocious words bewilder and bamboozle conscientious keyboard warriors daily.",
    "Pseudopseudohypoparathyroidism perplexes pneumonoultramicroscopicsilicovolcanoconiosis enthusiasts.",
    "Floccinaucinihilipilification of antidisestablishmentarianism is an onomatopoetic tongue twister.",
    "Bewitching syzygy juxtaposes quixotic zephyrs with rhombic dodecahedra and chrysanthemum phyllotaxis.",
    "The ineffable labyrinthine idiosyncrasies of sesquipedalian perspicacity tantalize indefatigable typists.",
    "A waxy sphinx box jig vexed the lazy dwarf; pack my box with five dozen liquor jugs, quickly!",
    "Sphinx of black quartz, judge my vow, while the jayhawk extols quirky rhythmic buzzwords.",
    "Crazy Fredericka bought many very exquisite opal jewels; jackdaws love my big sphinx of quartz.",
    "The sixth sick sheik's sixth sheep's sick, amidst bewildering rhythms and zephyr-like whizbangs.",
    "Sympathizing, unscrupulous, mischievous onlookers scrutinize unequivocally the incommunicable oeuvre.",
    "How quickly daft jumping zebras vex.",
    "The five boxing wizards jump quickly.",
    "Glib jocks quiz nymph to vex dwarf.",
    "Cwm fjord bank glyphs vext quiz.",
    "Woven silk pyjamas exchanged for blue quartz.",
    "Grumpy wizards make toxic brew for the evil queen and jack.",
    "Honorificabilitudinitatibus appears in Shakespeare's play.",
    "Hydrochlorofluorocarbons photolithographically crystallize zeolites.",
    "Thyroparathyroidectomized patients exhibit extraordinary electrophysiology.",
    "Unquestionably, subdermatoglyphic rhythms synchronize with xylophone jazz.",
  ],
};


